on:
  push:
    branches:
      - master



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Testing printing before'
        run: ls
      - uses: actions/checkout@v3  
      - name: 'Testing printing after'
        run: ls